### ISSUE TITLE
Multiple sensors 

### ISSUE THREAD

**Issue by sorford638** [Shmoopty/rpi-appliance-monitor#10]
Hi, I added this to the closed topic on running two sensors. However, since it is closed I wasn't sure if you would have been notified. My apologies if this isn't the correct way to do it! Thanks again, Steve 

Hi,

You gae me some great advice last month and my parts finally arrived today so I've been tinkering all evening. However, I can only get one sensor working. I've checked the components by swapping the wires and sensors around but I can only get the dryer sensor to work. It seems like no coincidence that this is the one that you gave the detailed instructions for!

In my setup I've got three sensors and I've made three copys of the python script (is this necessary?) and three settings files to go with them. I've then added the details to rc.local using the same format as you. I've attached photos to show where I'm at.

I'm sure that my mistake is glaringly obvious but I just can't see it!

Thanks again for your help,
Steve

https://cloud.githubusercontent.com/assets/10810507/23817041/8f43bf52-05f0-11e7-8c51-1c064ff0c0b5.png

https://cloud.githubusercontent.com/assets/10810507/23817054/9f450618-05f0-11e7-8cd7-73c8028cc47c.png

**Comment by sorford638** [comment]
I'm an idiot.  I was using the GPIO pin numbers of a Pi3 with a PiB+.

**Comment by Shmoopty** [comment]
That's good to hear! I hadn't decided how to best approach your problem yet, and you beat me to it!

Now it's clear what I have to do: update the instructions so everyone sees the right GPIO layout!  Thanks for following up with that solution.
