### ISSUE TITLE
Tweepy not downloading?

### ISSUE THREAD

**Issue by bengt-a** [Shmoopty/rpi-appliance-monitor#11]
Hi,
I'm so excited about this project! But when I try to follow your instructions for creating the software, I get the following error:

> pi@laundrypi:~ $ sudo pip install requests tweepy slackclient
> Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages
> Downloading/unpacking tweepy
>   Cannot fetch index base URL https://pypi.python.org/simple/
>   Could not find any downloads that satisfy the requirement tweepy
> Cleaning up...
> No distributions at all found for tweepy
> Storing debug log for failure in /root/.pip/pip.log

Is this going to be a problem?

Kind regards,
Bengt

**Comment by Shmoopty** [comment]
Oh no!

Well, this line seems to be the heart of the problem.

> Cannot fetch index base URL https://pypi.python.org/simple/

I just checked, and that link is working... Is your​ Pi possibly not connected to the internet?

Shmoopty

**Comment by bengt-a** [comment]
Hahaha! So simple solution.
I'm confused though. I put the pi in the laundry room, and connected via
SSH over wifi. So I assumed that if I could connect to it, it could also
connect to the world. Well, apparently not. This morning I brought it in
and put it next to the router, and now tweepy installed fine.

Now all that remains is to connect the vibration sensor to the Pi (I had an
old B+ Pi lying around so I thought I could use it instead of buying yet
another Pi... :) ) and testing the whole thing! And for that I need to get
some connectors I apparently didn't have at home...

Cheers,
Bengt

**Comment by Shmoopty** [comment]
Be sure to connect to the correct pins!  I think an old PiB+ uses a different GPIO pin layout than the diagram I link to.

Good luck!

**Comment by bengt-a** [comment]
Thanks! I have checked and double checked. According to what I can find,
for instance on this page (
http://www.raspberrypi-spy.co.uk/2012/06/simple-guide-to-the-rpi-gpio-header-and-pins/)
is that they have the same pinout - at least for 5V, GND, GPIO14 and 15. :)

Going to get connector cables tomorrow! So exciting! I have been dreaming
about a solution like this one for more than a year, but never gotten to
figuring out how to detect that the machine is finished. This seems like a
great solution.

**Comment by bengt-a** [comment]
Wohoooo! It works!!! You are the best, @Shmoopty !!!

Now I just need to figure out how to set the parameters so it only sends me a message when it is truly finished, since it runs in intervals. Perhaps setting seconds_to_end to a fairly high number, like 120, will do the trick...

**Comment by Shmoopty** [comment]
That's the way to do it for interval cycles, as far as I've been able to figure out.

Congratulations!

**Comment by bengt-a** [comment]
Thank you for this project!
You are a great source for inspiration, Sir! :)
