### ISSUE TITLE
Dual Sensors

### ISSUE THREAD

**Issue by chuff704** [Shmoopty/rpi-appliance-monitor#15]
I'm pretty novice at coding, just wondering how would you setup a second sensor?

**Comment by Shmoopty** [comment]
That won't require any additional coding.

Take a look at the README again.  Three times, you'll see "Multiple sensor expert mode" with the necessary steps to monitor 2 or more sensors from the same device.

Good luck!

**Comment by yostie** [comment]
Make sure you get/make some 3 pin jumper wires to go from the Pi to the sensors then attach the sensors to the appliances.  

Got my jumpers today and started testing.  My problem right now is that during some of the washer cycles, it trips the dryer sensor.  Tried increasing the vibration detection time on the dryer to like 60 seconds to outlast the more violent washer cycles but when I actually run the dryer the stupid thing doesn't vibrate enough consistently for that duration to trigger.  More testing I guess!
