### ISSUE TITLE
"If that doesn't help, read on..."

### ISSUE THREAD

**Issue by bickyb** [Shmoopty/rpi-appliance-monitor#17]
I was reading through the readme and there is a section that says: "Give it a little twist (probably in the "unscrew" direction) to make it less touchy. If that doesn't help, read on..."  
I think you meant to elaborate about the section of how to make the device less sensitive, but I don't see the subsequent session that is being referred to.

**Comment by Shmoopty** [comment]
If that doesn't help, modify your settings file to change seconds_to_end to a larger number. It should be longer than the rest cycle.
