### ISSUE TITLE
notification loop

### ISSUE THREAD

**Issue by tommetje** [Shmoopty/rpi-appliance-monitor#18]
First of all, thank you for sharing this great project! I have followed the instructions and I have got a working sensor.

My sensor is a little too happy to provide me with notifications however. Initially it worked fine but after a few days it, randomly, starts to send a lot of notifications after each other. It seems to be stuck in a loop. To end this I reboot the device.
Even after reinstalling everything I still have the problem.

I hope that someone could give me some hints on how to fix the notification flood.

I am only using IFTTT and the following settings:
seconds_to_start = 60 
seconds_to_end = 420

**Comment by Shmoopty** [comment]
I think you fell victim to some bad code that got merged in.  :(

There was a change to the code to optionally support light sensors, but I don't think the code was very stable.  I have now rolled that change back!

Please download "vibration.py" again and copy the new one to your device.  And please - let me know if your new invention is then behaving for you!

- Shmoopty

**Comment by tommetje** [comment]
I have tested the new code, it works great!
Thank you!

**Comment by Shmoopty** [comment]
Closing as fixed.
