### ISSUE TITLE
Use a virtualenv

### ISSUE THREAD

**Issue by nils-werner** [Shmoopty/rpi-appliance-monitor#2]
Please don't teach people to use `sudo pip install`, instead teach them how to use `virtualenv`.

**Comment by Shmoopty** [comment]
That's interesting.  Nobody has taught me how to use `virtualenv` though, so I would certainly be an awful teacher.

Do you recommend this because it is a good habit to make?  Or because it is more suitable for a single-purpose device like this?

**Comment by nils-werner** [comment]
> Do you recommend this because it is a good habit to make?

Yes.

 - It helps isolating different projects and their installed pip-packages (sometimes those requirements conflict).
 - It allows quickly destroying an environment if it is broken or if you want to test if it reinstalls as expected.
 - It allows non-root users to install packages comfortably (there is `--user`, but that's a bit messy to use)
 - It doesn't pollute your Linux system libraries (all packages are installed in the virtualenv, not in `/usr/lib/...`)
 - It encourages to not use `sudo` just because "without `sudo` it failed".

> Or because it is more suitable for a single-purpose device like this?

No, it is actually more for multi-purpose devices, like several projects on your dev workstation. But for single-purpose devices it doesn't make a difference, its just two commands more and then a different location where stuff gets installed.
