### ISSUE TITLE
MQTT Support

### ISSUE THREAD

**Issue by y8s** [Shmoopty/rpi-appliance-monitor#22]
warning: I'm no coder

Would be nice to see this have MQTT support included along with the other options. I'm sure lots of people would love a way to relay a "publish" message to e.g. another pi running mosquitto.

I was going to attempt to do this myself using some details from here:
https://tutorials-raspberrypi.com/raspberry-pi-mqtt-broker-client-wireless-communication/ 
And adding the appropriate settings/variables to the ini file.

It would allow you to send periodic status data to the MQTT server or on-demand query to determine if the machine is on or off instead of waiting for the end of cycle push notification.

**Comment by Shmoopty** [comment]
A fearless coder @migmailer has added this functionality!  Yay!

**Comment by y8s** [comment]
Thanks @migmailer ! That's fantastic. I will try it out when I figure out why my pi keeps shutting itself off.
