### ISSUE TITLE
Slack Integration Non-functional

### ISSUE THREAD

**Issue by nsmichael82** [Shmoopty/rpi-appliance-monitor#27]
I was not able to get the Slack integration to work at all.  

Also, this happens when I run the program:

File "/home/pi/vibration.py", line 178, in <module>
send_alert(config.get('main', 'BOOT_MESSAGE'))
File "/home/pi/vibration.py", line 104, in send_alert
slack_webhook(message)
TypeError: 'str' object is not callable

**Comment by Shmoopty** [comment]
Closing, as presumed fixed now.
