### ISSUE TITLE
Country in wpasupplicant.conf

### ISSUE THREAD

**Issue by cbrodine** [Shmoopty/rpi-appliance-monitor#29]
Just a small suggested update to the install guide.  The "county=US" (or whatever country) needs to be the first line in the wpasupplicant.conf file for the raspberry pi zero w and newer raspberry pi models or the wifi won't connect.

Thanks for the great software and guide!

**Comment by Shmoopty** [comment]
That sounds like good advice.  Thanks for sharing, cbrodine!
