### ISSUE TITLE
Questions regarding set up to send emails

### ISSUE THREAD

**Issue by rescuemoe** [Shmoopty/rpi-appliance-monitor#36]
Thank you for his wonderful code. I am planning on using to to alert me when my sump stay on to long due to faulty float valve not going down as the pump should only be on for a few second.
Is there functionality to have it send out an email. I already have my PI set up to send an emails from a command line. I would like to be able to add some code to to start_message to send an email instead of the the current options.  I was looking to just input something like this "echo "Pump ON to long" | ssmtp -s Subject myemail@gmail.com" .
Anybody have any thoughts on where in the code i would be able to insert thank to get it to work or if there are other commands that need to be added. 
Thanks to any advice or help anybody can provide

**Comment by Shmoopty** [comment]
Implemented!
