### ISSUE TITLE
801s's ... Where to find them?

### ISSUE THREAD

**Issue by crossoft** [Shmoopty/rpi-appliance-monitor#4]
Sorry for the uneducated question.  I haven't found a single "in stock" one like the photos (4-pin).  Tons of 2-pin vibration sensors out there, but not sure if they'll work with this.  Any suggestions?  Maybe I'm looking in the wrong places.

**Comment by Shmoopty** [comment]
You'll want to get a sensor that includes a tiny logic board for these particular instructions to work.  They all seem to include a screwdriver-controlled sensitivity adjustor that may prove useful.  **3-pin sensors will work as well**, as the sensor in my photos is includes an analog sensor that is entirely ignored.

Amazon is showing me some in-stock sellers for the 3-pin variety.  I can't say whether those sellers disappear if you're outside of the U.S.

Good luck!
