### ISSUE TITLE
Raspberry Pi Zero W GPIO Voltage

### ISSUE THREAD

**Issue by rdgerken** [Shmoopty/rpi-appliance-monitor#40]
Thank you for sharing this project.

Your guide shows driving the GPIO on the Pi Zero with 5V.  Shouldn't you be using the 3.3V pin?

**Comment by Shmoopty** [comment]
Using the 3.3v pin seems to be the appropriate choice, now that I've done some research.

I should change the directions to reflect that.

Thank you for bringing this to my attention, @rdgerken

**Comment by HITChris** [comment]
Pardon my ignorance, but is the 5V pin a hazard to the PCB or 801s?

- a rookie using the 3.3V and both 5V for three sensors.

**Comment by rdgerken** [comment]
> Pardon my ignorance, but is the 5V pin a hazard to the PCB or 801s?
> 
> * a rookie using the 3.3V and both 5V for three sensors.

I believe it's just an issue for the PCB - the GPIO pins are designed for 3.3V, not 5V.
