### ISSUE TITLE
SW-420 in place of 801s

### ISSUE THREAD

**Issue by dinki** [Shmoopty/rpi-appliance-monitor#48]
First, thanks for making this available.  I've been wanting to automate my dryer notifications for a long time now and this looks like it would fit the bill just fine.

I looked through my junk bin and found a Pi Zero and a SW-420 (https://components101.com/sensors/sw-420-vibration-sensor-module).  Can you tell me if this can be used in place of the 801s?  I'm not an EE but I can see that they are both using an LM393 comparator.

**Comment by Shmoopty** [comment]
Hi, @dinki !

That certainly looks like the right kind of component.  The specs are correct -- the only thing I can't certify is how sensitive it is.

Can you hear or feel a faint rattle when you wiggle the sensor?  If so, I'm pretty confident that you have what you need.

Regardless -- if you try it, can you let me know if the sensor worked for you?  I'd love to expand my instructions with more sensor options!

Cheers,

Shmoopty

**Comment by dinki** [comment]
I gave it a try and it works like a charm.  The only thing of note is that VCC and Data pins are different than the 801s so the user should be cautioned of this in the documentation.  Other than that it appears to work fine on my bench.  Will test it on the dryer later today.  Again, thank you!

**Comment by Shmoopty** [comment]
That's great news.  Congratulations!

**Comment by dinki** [comment]
Me again.  Here with an update.  The two SW-420 I tried were very inconsistent when I actually used them with the dryer.  I purchased the 801s and received it today.  I plugged it in and it worked as advertised.  I would advise against using the SW-420.  I believe that's why they were in my junk bin but now they are in the garbage.

**Comment by Shmoopty** [comment]
Thanks.  I appreciate you sharing this.
