### ISSUE TITLE
3 pin 801s

### ISSUE THREAD

**Issue by sorford638** [Shmoopty/rpi-appliance-monitor#5]
Hi, this looks like a great project and, for once, has actually got my wife excited about my gadgeteering! 
I've been looking at 801s sensors and I've found a 3 pin sensor (https://www.amazon.co.uk/gp/aw/d/B00NNDBMTY/ref=ox_sc_act_image_1?smid=A1NBUX8FDB1DWX&psc=1). Will this work just as well and which pins should I connect it to? 
Thanks again for sharing your work, 
Steve

**Comment by Shmoopty** [comment]
3-pin sensors should work well.  The fourth "analog" pin on the sensor I had is never used.

The sensor you link to seems to label the voltage pin `+`, the ground pin `-`, and the digital sensor pin `Dout`.  That should help match what you have to the directions.

I also see a small gold potentiometer for adjusting sensitivity and I think I see an LED on that board that may light up to tell you that you've connected it correctly.

Good luck!

**Comment by sorford638** [comment]
Thanks for your help, that's great.

Just to be clear, I'm using two sensors on a Pi 1 B+.  So I could connect
the following;

Sensor 1
+ connects to pin 4
- connects to pin 6
dout (middle one) connects to pin 8

Sensor 2
+ connects to pin 4 (I assume I can connect two sensors in parallel or do I
need to use separate ground and live?)
- connects to pin 6
dout (middle one) connects to pin 10

Thanks again for your help and sorry for needing such detailed explanations.

All the best,
Steve

**Comment by Shmoopty** [comment]
That sounds like a solid plan, Steve. The voltage and ground can be shared, in my experience. 

If you save the soldering for last, you can ensure that all the other steps are correct. 

Good luck, and enjoy the project.

**Comment by sorford638** [comment]
Right, just ordered everything I need (unfortunately it will take over a
month to get here!).

Last question (possibly), is there a way to log the information coming in
through push bullet?  That way I can have a record of when devices were
used and for how long.

Thanks,
Steve

**Comment by Shmoopty** [comment]
There is, but that is outside of the scope of this project.

**Comment by sorford638** [comment]
Fair enough and thanks again for all your help.

Enjoy the weekend,
Steve
