### ISSUE TITLE
Maker vs Webhooks

### ISSUE THREAD

**Issue by ITCMD** [Shmoopty/rpi-appliance-monitor#50]
I'm wondering how one gets a maker key.
I have a webhooks key set up but I dont understand what maker is. It seems like "maker" is ifttt and and there is no way to get a key for it.

Probably missing something simple.

**Comment by Shmoopty** [comment]
Hm, it would seem that "Maker" is now either an outdated tech or an outdated term.

The IFTTT integration may need to go, unless someone has the bandwidth to update this project.

**Comment by ITCMD** [comment]
Alright. I'm using Pushbullet instead, although I'm having another issue with it (Ill post in a sec)
