### ISSUE TITLE
I keep getting no config specified

### ISSUE THREAD

**Issue by Ausmack** [Shmoopty/rpi-appliance-monitor#54]
![image](https://user-images.githubusercontent.com/91149392/136122484-f4dbc27c-d48b-4575-9e80-5363df49a8f0.png)

I keep getting this error and not sure what to do.  ALso would I be able to do this with a SW-420 Vibration sensor instead?

**Comment by Shmoopty** [comment]
Take a look at the instructions again.  The program expects a command-line parameter that specifies the configuration file to use.  If no configuration file is specified, that's the error you get.

I have not tried an SW-240 sensor.  If it works for you, please let us know!

**Comment by Ausmack** [comment]
> Take a look at the instructions again. The program expects a command-line parameter that specifies the configuration file to use. If no configuration file is specified, that's the error you get.
> 
> I have not tried an SW-240 sensor. If it works for you, please let us know!

Could it be that I'm using a rpi4?  I've put way too many hours into this.  I've followed the instructions numerous times exactly and have formatted the card numerous times and it still won't work.  I'm just not sure why.

**Comment by Shmoopty** [comment]
RPi4 works.

From your screenshot, it looks like you are running

    ./vibration.py

When you should be running

    ./vibration.py vibration_settings.ini

The error you are getting was added to tell users that they did not specify a configuration file.

**Comment by Shmoopty** [comment]
I suspect that I know what the problem is.  Please give me a few hours to investigate.

**Comment by Ausmack** [comment]
> I suspect that I know what the problem is. Please give me a few hours to investigate.

Any luck?

**Comment by Shmoopty** [comment]
Hi, @Ausmack.

Grab a new copy of vibration.py and I think things will work better.  Good luck!

**Comment by Ausmack** [comment]
> Hi, @Ausmack.
> 
> Grab a new copy of vibration.py and I think things will work better. Good luck!

It works!!!!! Thank you so much!
