### ISSUE TITLE
No config file specified

### ISSUE THREAD

**Issue by oneharrydude** [Shmoopty/rpi-appliance-monitor#6]
I keep on getting 'No config file specified' when I run the python script. How do I resolve this issue?

**Comment by Shmoopty** [comment]
That would imply that the configuration file is misspelled or in the wrong directory. Or the file permissions prevent it from being opened. 

It's saying "I can't open that file". 

Good luck!

**Comment by oneharrydude** [comment]
Wow, thanks for getting back so quickly. I've doubled checked everything. Everything is named correctly and my vibration.py  and vibration_settings.ini are in /home/pi. File permissions are set to 'Anyone'.... The only changes I made to your initial python script was removing the twitter section since I don't need that, but that shouldn't be making a difference. Do I need to put these files elsewhere? How does the intial vibration.py know where my settings file is located? Thanks again for the help.

**Comment by Shmoopty** [comment]
The settings file must be specified on the command line. Read the instructions to the end to see how the script should be run.
